#include <jni.h>
#include <atomic>
#include <string>
#include <fstream>
#include <algorithm>
#include <android/log.h>
#include "dosbox_audio.h"

// External entry point declarations provided by the fetched DOSBox library source
extern int dosbox_main_entry(int argc, char* argv[]);

namespace {
std::atomic<bool> g_running{false};
DosboxAudioEngine g_audio;
std::atomic<int> g_cpu_cycles{35000};
std::atomic<int> g_frame_cap{60};
std::atomic<int> g_thermal_level{0};
std::atomic<float> g_mock_fps{60.0f};
std::atomic<float> g_mock_cpu{42.0f};

#define LOG_TAG "RetroRTS_JNI"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

int effective_cycles() {
    int base = g_cpu_cycles.load();
    int thermal = g_thermal_level.load();
    if (thermal >= 3) return std::max(8000, base / 3);
    if (thermal == 2) return std::max(12000, base / 2);
    if (thermal == 1) return std::max(18000, (base * 3) / 4);
    return base;
}
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_retrorts_ui_DosboxBridge_startDosboxNative(JNIEnv* env, jobject, jstring gameDir, jstring configPath) {
    if (g_running.load()) return JNI_TRUE;

    if (gameDir == nullptr || configPath == nullptr) return JNI_FALSE;
    const char* game_dir_c = env->GetStringUTFChars(gameDir, nullptr);
    const char* config_path_c = env->GetStringUTFChars(configPath, nullptr);
    if (game_dir_c == nullptr || config_path_c == nullptr) return JNI_FALSE;

    LOGI("Booting core engine. Game Dir: %s, Config Path: %s", game_dir_c, config_path_c);

    // Dynamic Cycle Tuning logic for high-demand Win9x RTS environments
    std::string pathStr(game_dir_c);
    if (pathStr.find("Dune2000") != std::string::npos || pathStr.find("dune") != std::string::npos) {
        g_cpu_cycles.store(35000); // Dune 2000 hardware execution profile baseline
        LOGI("Optimizing CPU cycles for Dune 2000 runtime footprint: 35000 cycles.");
    } else if (pathStr.find("cnc") != std::string::npos || pathStr.find("RedAlert") != std::string::npos) {
        g_cpu_cycles.store(30000); // Command & Conquer / Red Alert baseline profile
        LOGI("Optimizing CPU cycles for Command & Conquer runtime footprint: 30000 cycles.");
    }

    g_audio.start(48000, 2);
    g_running.store(true);

    // Prepare arguments to pass directly into the underlying DOSBox initialization sequence
    // It configures the engine to boot automatically using the unique profile .conf file generated by Android
    const char* args[] = {
        "dosbox",
        "-conf",
        config_path_c,
        "-exit" // Prevents the emulator from hanging on a terminal exit prompt when a game closes
    };

    int result = dosbox_main_entry(4, const_cast<char**>(args));

    env->ReleaseStringUTFChars(gameDir, game_dir_c);
    env->ReleaseStringUTFChars(configPath, config_path_c);

    if (result != 0) {
        LOGI("Native core engine initialization failed with code: %d", result);
        g_running.store(false);
        g_audio.stop();
        return JNI_FALSE;
    }

    return JNI_TRUE;
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_stopDosboxNative(JNIEnv*, jobject) {
    if (!g_running.load()) return;
    g_audio.stop();
    g_running.store(false);
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_submitAudioPcm16Native(JNIEnv* env, jobject, jshortArray buffer, jint frames, jint channels) {
    if (!g_running.load() || buffer == nullptr) return;
    jshort* ptr = env->GetShortArrayElements(buffer, nullptr);
    g_audio.submitPcm16(reinterpret_cast<int16_t*>(ptr), frames, channels);
    env->ReleaseShortArrayElements(buffer, ptr, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_setVolumeNative(JNIEnv*, jobject, jfloat volume) { g_audio.setVolume(volume); }

extern "C" JNIEXPORT jboolean JNICALL Java_com_retrorts_ui_DosboxBridge_saveStateNative(JNIEnv* env, jobject, jstring gameId, jint slot, jstring path) {
    if (gameId == nullptr || path == nullptr) return JNI_FALSE;
    const char* game_id = env->GetStringUTFChars(gameId, nullptr);
    if (path == nullptr) return JNI_FALSE;
    const char* save_path = env->GetStringUTFChars(path, nullptr);
    if (save_path == nullptr) return JNI_FALSE;
    if (game_id == nullptr || save_path == nullptr) return JNI_FALSE;
    std::ofstream out(save_path, std::ios::binary);
    bool ok = false;
    if (out.good()) { out << "GAME=" << game_id << "\nSLOT=" << slot << "\nSTATE=PLACEHOLDER\n"; ok = true; }
    out.close();
    env->ReleaseStringUTFChars(gameId, game_id);
    env->ReleaseStringUTFChars(path, save_path);
    return ok ? JNI_TRUE : JNI_FALSE;
}

extern "C" JNIEXPORT jboolean JNICALL Java_com_retrorts_ui_DosboxBridge_loadStateNative(JNIEnv* env, jobject, jstring, jint, jstring path) {
    if (path == nullptr) return JNI_FALSE;
    const char* save_path = env->GetStringUTFChars(path, nullptr);
    if (save_path == nullptr) return JNI_FALSE;
    std::ifstream in(save_path, std::ios::binary);
    bool ok = in.good();
    in.close();
    env->ReleaseStringUTFChars(path, save_path);
    return ok ? JNI_TRUE : JNI_FALSE;
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_setCpuCyclesNative(JNIEnv*, jobject, jint cycles) {
    g_cpu_cycles.store(std::clamp(static_cast<int>(cycles), 5000, 200000));
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_setFrameCapNative(JNIEnv*, jobject, jint fps) {
    g_frame_cap.store(std::clamp(static_cast<int>(fps), 30, 120));
    g_mock_fps.store(static_cast<float>(g_frame_cap.load()));
}

extern "C" JNIEXPORT void JNICALL Java_com_retrorts_ui_DosboxBridge_notifyThermalLevelNative(JNIEnv*, jobject, jint level) {
    g_thermal_level.store(std::clamp(static_cast<int>(level), 0, 3));
    const int eff = effective_cycles();
    const float ratio = static_cast<float>(eff) / static_cast<float>(std::max(1, g_cpu_cycles.load()));
    g_mock_cpu.store(35.0f * ratio + 20.0f);
}

extern "C" JNIEXPORT jfloatArray JNICALL Java_com_retrorts_ui_DosboxBridge_getPerfStatsNative(JNIEnv* env, jobject) {
    jfloatArray arr = env->NewFloatArray(2);
    float values[2] = {g_mock_fps.load(), g_mock_cpu.load()};
    env->SetFloatArrayRegion(arr, 0, 2, values);
    return arr;
}
