name: Android CI Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Clone DOSBox source
        run: |
          git clone --depth=1 https://github.com/dosbox-staging/dosbox-staging.git \
          RetroRTS/app/src/main/cpp/dosbox

      - name: Build with Gradle
        run: |
          cd RetroRTS
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: RetroRTS/app/build/outputs/apk/debug/
